### ISSUE TITLE
If player is sitting at a seat, that seat should be selected when the page is reloaded

### ISSUE THREAD

**Issue by benjaminpjones** [benjaminpjones/govariants#85]
It rememebers you are sitting at the seat, but not which player was selected (you can sit at multiple seats, hence the selection after sitting)

**Comment by JonKo314** [comment]
Suggestion:
* If a user isn't occupying a seat, no seat is selected (obviously).
* If a user is occupying exactly one seat, that seat is selected.
* If a user is occupying multiple seats, but only at one of them the user is currently allowed to make a move, that seat is selected.
* Otherwise no seat is selected, to prevent misclicks. Or is this inconvenient?

**Comment by benjaminpjones** [comment]
Yep, the first two bullet points are must-have.  How we deal with someone sitting at multiple seats is less important, but I think what you proposed is good!

**Comment by JonKo314** [comment]
> * If a user is occupying multiple seats, but only at one of them the user is currently allowed to make a move, that seat is selected.

I think that would require to change the base class `AbstractGame` because it doesn't have a property that tells whose turn it is yet. But I'll close this issue with my PR, so if we want that feature, we'll have to make a new issue.
